version: "1"
services:
  databaseapi:
    image: databaseapi
    ports:
      - "8080:8080"
    networks:
      - employee-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    networks:
      - employee-net
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=employeedb

networks:
  employee-net: